examination/urls.py
from django.urls import path
from . import views

app_name = 'examination'

urlpatterns = [
    path("", views.index, name="index"),
    path('persons/', views.get_persons, name='persons'),
    path('persons/<int:person_id>/', views.get_person, name='person_detail'),
    path('persons/<int:person_id>/delete/', views.delete_person, name='delete_person'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from .views import home

urlpatterns = [
    path('', home, name='home'),
    path("quiz/", include("quiz.urls")),
    path("examination/", include("examination.urls")),
    path("admin/", admin.site.urls),
]

quiz/urls.py
from django.urls import path

from . import views

app_name = 'quiz'

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("<int:pk>/", views.DetailView.as_view(), name="detail"),
    path("<int:pk>/results/", views.ResultsView.as_view(), name="results"),
    path("<int:question_id>/vote/", views.vote, name="vote"),
]

examination/models.py
from datetime import datetime
from django.db import models


class BaseModel(models.Model):
    objects = models.Manager()

    class Meta:
        abstract = True


class Person(BaseModel):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=100)
    birth_day = models.DateField(default=datetime(year=2000, month=1, day=1))

    def __str__(self):
        return f'{self.first_name} {self.last_name}'


class Exam(BaseModel):
    subject = models.CharField(max_length=50)
    topic = models.CharField(max_length=50)

    def __str__(self):
        return f'{self.subject} {self.topic}'


class Question(BaseModel):
    question = models.CharField(max_length=100)
    difficulty = models.CharField(max_length=100)

    def __str__(self):
        return f'{self.question} {self.difficulty}'


class TestQuestion(BaseModel):
    exam = models.ForeignKey(Exam, on_delete=models.CASCADE)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.exam} {self.question}'


class Answer(BaseModel):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    answers = models.CharField(max_length=100)
    correct = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.question} {self.answers} {self.correct}'


class Result(BaseModel):
    person = models.ForeignKey(Person, on_delete=models.CASCADE)
    exam = models.ForeignKey(Exam, on_delete=models.CASCADE)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    person_answer = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.person} {self.exam} {self.question} {self.person_answer}'

"""
tests
id
subject
topic
"""

quiz/models.py
from django.db import models


class BaseModel(models.Model):
    objects = models.Manager()

    class Meta:
        abstract = True


class Question(BaseModel):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField("date published")

    def __str__(self):
        return self.question_text


class Choice(BaseModel):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

examination/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views import generic


from django.shortcuts import render
from django.http import  HttpResponse
from .models import *

def index(request):
    return HttpResponse("Cia yra examination")


def get_persons(request):
    persons = Person.objects.all()
    context = {'persons': persons}
    return render(request, 'examination/persons.html', context)


def get_person(request, person_id):
    person = get_object_or_404(Person, id=person_id)
    context = {'person': person}
    return render(request, 'examination/person_detail.html', context)


def delete_person(request, person_id):
    person = get_object_or_404(Person, id=person_id)

    if request.method == 'POST':
        person.delete()
        return redirect('examination:persons')

    context = {'person': person}
    return render(request, 'examination/person_delete.html', context)

mysite/views.py
from django.shortcuts import render

def home(request):
    return render(request, 'home/home.html')

quiz/views.py
from django.db.models import F
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic

from .models import Choice, Question


class IndexView(generic.ListView):
    template_name = "quiz/index.html"
    context_object_name = "latest_question_list"

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.order_by("-pub_date")[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = "quiz/detail.html"


class ResultsView(generic.DetailView):
    model = Question
    template_name = "quiz/results.html"


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST["choice"])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(
            request,
            "quiz/detail.html",
            {
                "question": question,
                "error_message": "You didn't select a choice.",
            },
        )
    else:
        selected_choice.votes = F("votes") + 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse("quiz:results", args=(question.id,)))

examination/templates/examination/person_add.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

examination/templates/examination/person_delete.html
{% extends 'home/base.html' %}

{% block title %}Confirm Delete{% endblock %}

{% block content %}
    <h1>Confirm Delete</h1>
    <p>Are you sure you want to delete {{ person.first_name }} {{ person.last_name }}?</p>
    <form method="post" action="{% url 'examination:delete_person' person.id %}">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Delete</button>
        <a href="{% url 'examination:persons' %}" class="btn btn-secondary">Cancel</a>
    </form>
{% endblock %}

examination/templates/examination/person_detail.html
{% extends 'home/base.html' %}

{% block title %}Person Detail{% endblock %}

{% block content %}
    <h1>{{ person.first_name }} {{ person.last_name }}</h1>
    <p>Birthday: {{ person.birth_day }}</p>
    <a href="{% url 'examination:delete_person' person.id %}" class="btn btn-danger">Delete Person</a>
    <a href="{% url 'examination:persons' %}" class="btn btn-secondary">Back to Persons List</a>
{% endblock %}

examination/templates/examination/person_update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

examination/templates/examination/persons.html
{% extends 'home/base.html' %}

{% block content %}
<h1> People </h1>
    <table class="table table-dark table-striped">
  <thead>
    <tr>
      <th scope="col">No.</th>
      <th scope="col">Name</th>
      <th scope="col">Last name</th>
      <th scope="col">Birth date</th>
    </tr>
  </thead>
  {% for person in persons %}
  <tbody>
    <tr>
      <th scope="row">{{ forloop.counter }}</th>
      <td> {{person.first_name}} </td>
      <td> {{person.last_name}} </td>
      <td> {{person.birth_day}} </td>
    </tr>
  </tbody>
      {% endfor %}
</table>

{% endblock %}

quiz/templates/quiz/detail.html
{% extends 'home/base.html' %}
{% block content %}
<form action="{% url 'quiz:vote' question.id %}" method="post">
{% csrf_token %}
<fieldset>
    <legend><h1>{{ question.question_text }}</h1></legend>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
    {% endfor %}
</fieldset>
<input type="submit" value="Vote">
</form>
{% endblock %}

quiz/templates/quiz/index.html
{% extends 'home/base.html' %}

{% block content %}
    {% if latest_question_list %}
        <ul>
        {% for question in latest_question_list %}
            <li><a href="{% url 'quiz:detail' question.id %}">{{ question.question_text }}</a></li>
        {% endfor %}
        </ul>
    {% else %}
        <p>No quiz are available.</p>
    {% endif %}
{% endblock %}

quiz/templates/quiz/results.html
{% extends 'home/base.html' %}
{% block content %}
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'quiz:detail' question.id %}">Vote again?</a>
{% endblock %}

templates/home/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<header>
    <nav class="navbar bg-primary" data-bs-theme="dark">
        <nav class="navbar navbar-expand-lg bg-body-tertiary">
            <div class="container-fluid">
                <div class="collapse navbar-collapse" id="navbarText">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="{% url 'quiz:index' %}">Questions</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="{% url 'examination:index' %}">Examination</a>
                        </li>
                        <!-- Dropdown menu starts here -->
                        <li class="nav-item dropdown">
                            <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Exams
                            </button>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" href="{% url 'examination:persons' %}">Person</a></li>
                                <li><a class="dropdown-item" href="#">Another action</a></li>
                                <li><a class="dropdown-item" href="#">Something else here</a></li>
                            </ul>
                        </li>
                        <!-- Dropdown menu ends here -->
                    </ul>
                </div>
            </div>
        </nav>
    </nav>
</header>
<body>
    <div class="container">
        <br>
        {% block content %}
        {% endblock %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

templates/home/home.html
{% extends 'home/base.html' %}

{% block content %}
    <h2> Cia yra mano home page </h2>
{% endblock %}